### ISSUE TITLE
Not possible to run via the cli interface

### ISSUE THREAD

**Issue by rvanlaar** [WerWolv/PatternLanguage#61]
A valid command to the imhex pattern language cli results in the following message:

```
$ imhex --pl run -i ../examples/diadisc.mov -p small.hexpat -v
The following argument was not expected: imhex
Run with --help for more information.
```

When an invalid command is run, e.g. missing input file there is an actual error message:
```
$ imhex --pl run -p small.hexpat
--input is required
Run with --help for more information.
```

**Comment by WerWolv** [comment]
Fixed in latest ImHex commit

**Comment by rvanlaar** [comment]
This problem still exists when running the `plcli` in stand alone mode.

`plcli format -i test.txt -p test.hexpat -o test.json
The following argument was not expected: plcli
Run with --help for more information`

**Comment by paxcut** [comment]
today i compiled the plcli onwdl3 using ubuntu 22.04 and tried the command
```cpp
plcli format -I /usr/share/imhex/includes -i octagr_2.mov -p spiel.hexpat out.json
```
which  ran without errors and produced what seems to be the right answer.

**Comment by rvanlaar** [comment]
Maybe the commands I executed to compile it, weren't correct. Can you elaborate which steps you executed to compile it?

**Comment by WerWolv** [comment]
I fixed this issue today again so the plcli should work too now

**Comment by paxcut** [comment]
yes, I was testing it on linux and windows and both seem to work .

**Comment by paxcut** [comment]
Actually for `plcli.exe` the bug was never fixed and I had to take out the executable from the list if arguments before parsing them. I was in the middle of getting it to compile and must have been tired cause i forgot until now. Feel free to change it or I could do a pr but that seems excessive to turn a zero into a one.

**Comment by rvanlaar** [comment]
Awesome, can confirm it works.
